package com.kerybotu.derpibooru.mirror.ui

import android.content.Intent
import android.content.res.ColorStateList
import android.os.Bundle
import android.view.Gravity
import android.widget.*
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.app.AppCompatActivity
import com.bumptech.glide.Glide
import com.google.android.material.tabs.TabLayout
import com.kerybotu.derpibooru.mirror.PaletteManager
import com.kerybotu.derpibooru.mirror.R
import com.kerybotu.derpibooru.mirror.auth.ApiKeyStore
import com.kerybotu.derpibooru.mirror.download.DownloadQueueManager
import com.kerybotu.derpibooru.mirror.favorites.*
import com.kerybotu.derpibooru.mirror.model.Image
import com.kerybotu.derpibooru.mirror.network.NetworkManager
import kotlinx.coroutines.*
import org.json.JSONObject
import java.net.URLEncoder

class FavoritesActivity : AppCompatActivity() {
    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.Main)
    private lateinit var content: LinearLayout; private lateinit var scroll: ScrollView; private lateinit var toolbar: SafeToolbar; private lateinit var store: LocalFavoritesStore
    private var folder: FavoriteFolder? = null; private val chosen = mutableSetOf<Int>(); private var showingServer=false; private var serverPage=1; private var serverLoading=false; private var serverMore=true; private val serverItems=mutableListOf<FavoriteItem>()
    override fun onCreate(s: Bundle?) { super.onCreate(s); store=LocalFavoritesStore(this); setContentView(build()); folders() }
    private fun build()=LinearLayout(this).apply { val c=PaletteManager.colors(this@FavoritesActivity);orientation=LinearLayout.VERTICAL;setBackgroundColor(c.surface);toolbar=SafeToolbar(this@FavoritesActivity).apply{title="收藏夹";setNavigationIcon(R.drawable.ic_arrow_back);setNavigationOnClickListener{if(folder!=null)folders()else finish()}};addView(toolbar,LinearLayout.LayoutParams(-1,d(56)));addView(TabLayout(this@FavoritesActivity).apply{setBackgroundColor(c.surfaceVariant);tabTextColors=ColorStateList(arrayOf(intArrayOf(android.R.attr.state_selected),intArrayOf()),intArrayOf(c.primary,c.onSurface));setSelectedTabIndicatorColor(c.primary);addTab(newTab().setText("本地收藏夹"));addTab(newTab().setText("Derpibooru收藏"));addOnTabSelectedListener(object:TabLayout.OnTabSelectedListener{override fun onTabSelected(t:TabLayout.Tab){if(t.position==0)folders()else server(true)};override fun onTabUnselected(t:TabLayout.Tab){};override fun onTabReselected(t:TabLayout.Tab){}})});content=LinearLayout(this@FavoritesActivity).apply{orientation=LinearLayout.VERTICAL;setPadding(d(16),d(12),d(16),d(24))};scroll=ScrollView(this@FavoritesActivity).apply{addView(content);viewTreeObserver.addOnScrollChangedListener{if(showingServer&&serverMore&&!serverLoading&&getChildAt(0).bottom-height-scrollY<d(500))server(false)}};addView(scroll,LinearLayout.LayoutParams(-1,0,1f)) }
    private fun folders(){showingServer=false;folder=null;chosen.clear();toolbar.menu.clear();toolbar.title="收藏夹";content.removeAllViews();content.addView(button("+ 新建文件夹"){prompt("新建收藏夹"){store.createFolder(it);folders()}});content.addView(button("导入 Derpibooru 收藏"){importFaves()});val grid=GridLayout(this).apply{columnCount=2;useDefaultMargins=true};store.allFolders().forEach{f->grid.addView(TextView(this).apply{val c=PaletteManager.colors(this@FavoritesActivity);text="★ ${f.name}\n${f.items.size} 项";gravity=Gravity.CENTER;textSize=16f;setPadding(d(8),d(28),d(8),d(28));setTextColor(c.onSurface);setBackgroundColor(c.surfaceVariant);setOnClickListener{inside(f)};setOnLongClickListener{menu(f);true}},GridLayout.LayoutParams().apply{width=0;columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f)})};content.addView(grid)}
    private fun menu(f:FavoriteFolder){val ops=if(f.isDefault)arrayOf("下载全部")else arrayOf("重命名","下载全部","删除收藏夹");AlertDialog.Builder(this).setTitle(f.name).setItems(ops){_,i->when(ops[i]){"重命名"->prompt("重命名收藏夹",f.name){store.renameFolder(f.id,it);folders()};"下载全部"->{DownloadQueueManager.get(this).enqueueImages(f.items.map{Image(it.imageId,"",it.thumbnailUrl,0,0,0,0,0,0,0,emptyList(),mimeType=it.format)});toast("已加入下载队列")};else->AlertDialog.Builder(this).setTitle("删除收藏夹？").setMessage("其中的本地收藏记录将被删除。此操作不可撤销。").setNegativeButton("取消",null).setPositiveButton("删除"){_,_->store.deleteFolder(f.id);folders()}.show()}}.show()}
    private fun inside(f:FavoriteFolder){folder=f;chosen.clear();toolbar.menu.clear();toolbar.title="${f.name}（${f.items.size}）";rows(f)}
    private fun rows(f:FavoriteFolder){content.removeAllViews();f.items.forEach{item->localRow(f,item)}}
    private fun localRow(f:FavoriteFolder,item:FavoriteItem){val c=PaletteManager.colors(this);val row=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(d(8),d(8),d(8),d(8));setBackgroundColor(if(chosen.contains(item.imageId))c.primary else c.surfaceVariant);setOnClickListener{if(chosen.isEmpty())open(item.imageId)else toggle(f,item.imageId)};setOnLongClickListener{toggle(f,item.imageId);true}};preview(row,item);row.addView(TextView(this).apply{text="图片 #${item.imageId}";setTextColor(c.onSurface);setPadding(d(12),0,0,0)},LinearLayout.LayoutParams(0,-2,1f));content.addView(row,LinearLayout.LayoutParams(-1,-2).apply{bottomMargin=d(8)})}
    private fun toggle(f:FavoriteFolder,id:Int){if(!chosen.add(id))chosen.remove(id);toolbar.menu.clear();toolbar.title=if(chosen.isEmpty())"${f.name}（${f.items.size}）"else"已选择 ${chosen.size} 项";if(chosen.isNotEmpty())toolbar.menu.add("删除").apply{setIcon(R.drawable.ic_delete);setShowAsAction(android.view.MenuItem.SHOW_AS_ACTION_ALWAYS);setOnMenuItemClickListener{confirmDelete(f);true}};rows(f)}
    private fun confirmDelete(f:FavoriteFolder){AlertDialog.Builder(this).setTitle("移除本地收藏？").setMessage("将从当前收藏夹移除已选择的 ${chosen.size} 张图片。").setNegativeButton("取消",null).setPositiveButton("删除"){_,_->chosen.forEach{store.remove(f.id,it)};chosen.clear();toolbar.menu.clear();inside(f)}.show()}
    private fun importFaves(){if(!ApiKeyStore.isLoggedIn(this)){toast("请先登录");return};scope.launch{val raw=withContext(Dispatchers.IO){NetworkManager.getApi(this@FavoritesActivity,"search/images?q=${URLEncoder.encode("my:faves","UTF-8")}&per_page=50")};val arr=runCatching{JSONObject(raw.orEmpty()).optJSONArray("images")}.getOrNull();val target=store.allFolders().first{it.isDefault};repeat(arr?.length()?:0){i->arr?.optJSONObject(i)?.let{o->store.add(target.id,FavoriteItem(o.optInt("id"),o.optJSONObject("representations")?.optString("small"),o.optString("mime_type")))}};toast("已导入 ${arr?.length()?:0} 张收藏")}}
    private fun server(reset:Boolean){showingServer=true;folder=null;if(!ApiKeyStore.isLoggedIn(this)){content.removeAllViews();content.addView(TextView(this).apply{text="登录后查看你的 Derpibooru 收藏";gravity=Gravity.CENTER;setTextColor(PaletteManager.colors(this@FavoritesActivity).muted);setPadding(0,d(80),0,d(80))});return};if(serverLoading||(!reset&&!serverMore))return;if(reset){serverPage=1;serverMore=true;serverItems.clear();content.removeAllViews()};serverLoading=true;scope.launch{val raw=withContext(Dispatchers.IO){NetworkManager.getApi(this@FavoritesActivity,"search/images?q=${URLEncoder.encode("my:faves","UTF-8")}&page=$serverPage&per_page=50")};val arr=runCatching{JSONObject(raw.orEmpty()).optJSONArray("images")}.getOrNull();repeat(arr?.length()?:0){i->arr?.optJSONObject(i)?.let{o->serverItems.add(FavoriteItem(o.optInt("id"),o.optJSONObject("representations")?.optString("small"),o.optString("mime_type")))}};serverMore=(arr?.length()?:0)>=50;if((arr?.length()?:0)>0)serverPage++;content.removeAllViews();serverItems.forEach{serverRow(it)};serverLoading=false}}
    private fun serverRow(item:FavoriteItem){val c=PaletteManager.colors(this);val row=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(d(8),d(8),d(8),d(8));setBackgroundColor(c.surfaceVariant);setOnClickListener{open(item.imageId)}};preview(row,item);row.addView(TextView(this).apply{text="图片 #${item.imageId}";setTextColor(c.onSurface);setPadding(d(12),0,0,0)});content.addView(row,LinearLayout.LayoutParams(-1,-2).apply{bottomMargin=d(8)})}
    private fun preview(row:LinearLayout,item:FavoriteItem){val image=ImageView(this).apply{scaleType=ImageView.ScaleType.CENTER_CROP};item.thumbnailUrl?.takeIf{it.isNotBlank()}?.let{Glide.with(this).load(it).into(image)};row.addView(image,LinearLayout.LayoutParams(d(76),d(76)))}
    private fun button(text:String,click:()->Unit)=Button(this).apply{this.text=text;val c=PaletteManager.colors(this@FavoritesActivity);setTextColor(c.onPrimary);backgroundTintList=ColorStateList.valueOf(c.primary);setOnClickListener{click()}}
    private fun prompt(title:String,initial:String="",done:(String)->Unit){val input=EditText(this).apply{setText(initial)};AlertDialog.Builder(this).setTitle(title).setView(input).setNegativeButton("取消",null).setPositiveButton("完成"){_,_->done(input.text.toString())}.show()}
    private fun open(id:Int)=startActivity(Intent(this,ImageDetailActivity::class.java).putExtra("image_id",id));private fun toast(v:String)=Toast.makeText(this,v,Toast.LENGTH_SHORT).show();private fun d(v:Int)=(v*resources.displayMetrics.density).toInt();override fun onDestroy(){scope.cancel();super.onDestroy()}
}
